contacts/urls.py
from django.urls import path

from contacts import views

app_name = 'contacts'

urlpatterns = [
    path("contact_me/", views.ContactsView.as_view(), name="contacts"),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='short_index'),
    path('index/', views.IndexView.as_view(), name='index'),
]

projects/urls.py
from django.urls import path
from projects import views


app_name = 'projects'

urlpatterns = [
    path("projects/", views.ProjectListView.as_view(), name="project-list"),
    path("progects/page/<int:page>", views.ProjectListView.as_view(), name="paginator"),
]

web_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path('', include('main.urls', namespace='main')),
    path('', include('contacts.urls', namespace='contacts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

projects/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=36)
    link = models.URLField()
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='projects_photos', default='/projects_photos/default.png')

    def __str__(self):
        return f'{self.id} - {self.title}'


class Skill(models.Model):
    name = models.CharField(max_length=36)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='skills')
    image = models.ImageField(upload_to='skills_photos')

    def __str__(self):
        return f'{self.project.title} - {self.name}'

common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        return context

contacts/views.py
from django.views.generic import TemplateView

from common.views import TitleMixin


class ContactsView(TitleMixin, TemplateView):
    template_name = 'contacts/contacts.html'
    title = "Contact me"

main/views.py
from django.views.generic import TemplateView

from common.views import TitleMixin


# Create your views here.
class IndexView(TitleMixin, TemplateView):
    template_name = 'main/index.html'
    title = "Main page"

projects/views.py
from django.views.generic import ListView

from projects.models import Project
from common.views import TitleMixin


# Create your views here.
class ProjectListView(TitleMixin, ListView):
    model = Project
    title = 'Projects'
    context_object_name = 'projects'
    template_name = 'projects/projects.html'
    paginate_by = 4

contacts/templates/contacts/contacts.html
{% extends 'main/base.html' %}

{% load static %}

{% block css %}
    <link href="{% static '/css/contacts.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <h1 class="title">Contact me</h1>
    <div class="main-block">

        <a href="https://t.me/lewiscarroll" class="card" target="_blank">
            <div class="card-text">
                Telegram: @lewiscarroll
            </div>
            <img class="card-image"
                 src="{% static '/icons/telegram-footer_dark.svg' %}"
                 alt="card-image">
        </a>
        <a href="https://www.linkedin.com/in/grister/" class="card" target="_blank">
            <div class="card-text">
                LinkedIn: @grister
            </div>
            <img class="card-image"
                 src="{% static '/icons/linkedin-footer_dark.svg' %}"
                 alt="card-image">
        </a>
        <a href="https://github.com/Grister/" class="card" target="_blank">
            <div class="card-text">
                GitHub: @grister
            </div>
            <img class="card-image"
                 src="{% static '/icons/github-footer_dark.svg' %}"
                 alt="card-image">
        </a>
        <a href="mailto:example@example.com" class="card" target="_blank">
            <div class="card-text">
                Email: carroll.lewi@gmail.com
            </div>
            <img class="card-image"
                 src="{% static '/icons/mail-footer_dark.svg' %}"
                 alt="card-image">
        </a>
    </div>
{% endblock %}

main/templates/main/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en" class="theme-light">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <script> const staticURL = "{% static '/icons' %}" + "/";</script>

    <link href="{% static '/css/base.css' %}" rel="stylesheet">
    {% block css %} {% endblock %}
</head>


<body>
    <div class="container-center-horizontal">
        <!-- {#        --------------Navbar flare--------------------------#} -->
        <header class="navbar">
            <div class="menu-btn">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <nav class="mobile-nav">
              <ul>
                <li><a href="{% url 'main:index' %}">Main page</a></li>
                <li><a href="{% url 'projects:project-list' %}">Projects</a></li>
                <li><a href="{% url 'contacts:contacts' %}">Contacts</a></li>
              </ul>
            </nav>
            <nav class="text-navbar">
                <a href="{% url 'main:index' %}" id="g-logo">
                    [g]
                </a>
                <a href="{% url 'main:short_index' %}" class="navbar-element" id="main-page">
                    Main page
                </a>
                <a href="{% url 'projects:project-list' %}" class="navbar-element" id="projects">
                    Projects
                </a>
                <a href="{% url 'contacts:contacts' %}" class="navbar-element" id="contacts">
                    Contacts
                </a>
            </nav>
            <div class="sidebar">
                <a href="https://github.com/Grister/web-portfolio" class="sidebar-element">
                    <img id="github"
                         src="{% static '/icons/github-footer_dark.svg' %}"
                         alt="github">
                </a>
                <img id="separator" class="separator"
                     src="{% static '/icons/séparateur.png' %}"
                     alt="separator">
                <label id="theme-switch" class="switch sidebar-element">
                    <input type="checkbox" onchange="toggleTheme()" id="slider">
                    <span class="slider round"></span>
                </label>
            </div>
        </header>

        <!-- {#        --------------Main section--------------------------#} -->
        <main class="main-content">
            {% block content %} {% endblock %}
        </main>

        <!-- {#        --------------Footer section--------------------------#} -->
        <footer class="footer">
            <div class="footer-box">
                <div class="footer-logo-box">
                    <div class="grist-logo">[g]rist</div>

                    <div class="copyright">
                        <p class="p-copyright">
                            © 2024 All Rights Reserved
                        </p>
                    </div>
                </div>

                <p class="footer-text">
                    Welcome to my personal website! Here you will find information about me,
                    my projects and contact information to get in touch with me.
                    You can also check out my portfolio and view my projects on GitHub.
                    I look forward to hearing from you!
                </p>

                <div class="footer-links">
                    <a href="mailto:carroll.lewi@gmail.com" class="footer-link" target="_blank">
                        <img id="mail-footer" class="mail footer-icon"
                             src=""
                             alt="mail"></a>
                    <a href="https://t.me/lewiscarroll" class="footer-link" target="_blank">
                        <img id="telegram-footer" class="telegram footer-icon"
                             src=""
                             alt="telegram"></a>
                    <a href="https://github.com/Grister/" class="footer-link" target="_blank">
                        <img id="github-footer" class="github footer-icon"
                             src=""
                             alt="Github"></a>
                    <a href="https://www.linkedin.com/in/grister/" class="footer-link" target="_blank">
                        <img id="linkedin-footer" class="linkedin footer-icon"
                             src=""
                             alt="linkedin">
                    </a>
                </div>
            </div>
        </footer>
    </div>

    <script src="{% static '/js/theme-switch.js' %}"></script>
    <script src="{% static '/js/links-settings.js' %}"></script>
</body>

</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block css %}
    <link href="{% static '/css/main-page.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="main-text">
        <h1 class="title">Zakhar Kravchenko</h1>
        <div class="position">Python Backend Developer</div>
        <p class="description">
            A junior Backend developer who wants to bring ideas to life through code, ensuring they seamlessly
            integrate into the digital landscape.
            I specialize in web application development with Python and its frameworks.
        </p>
        <div class="button-container">
            <a href="https://bucket-for-grister.s3.amazonaws.com/cv/CV_Zakhar_Kravchenko_Junior_Backend_Developer.pdf" class="cv-button button" target="_blank">
                <div class="cv-link">Download my CV</div>
            </a>
            <a href="{% url 'contacts:contacts' %}" class="contact-me-button button">
                <div class="contact-me-text">Contact me</div>
                <img class="telegram-icon-contact"
                     src="{% static '/icons/telegram-footer_dark.svg' %}"
                     alt="telegram">
            </a>
        </div>
    </div>
    <img class="photo-profile"
         src="{% static '/icons/coder.png' %}"
         alt="photo">

{% endblock %}

projects/templates/projects/projects.html
{% extends 'main/base.html' %}

{% load static %} -->


{% block css %}
    <link href="{% static '/css/projects.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
            <h1 class="title">My Projects</h1>

            <div class="main-block">
                {% for card in projects %}
                <div class="card">
                    <div class="card-body">
                        <div class="card-top-side">
                            <a href="{{ card.link }}" class="card-title" target="_blank">
                                <p>{{ card.title }}</p>
                            </a>
                            <ul class="side-skills">
                                {% for skill in card.skills.all %}
                                <li class="skill-item">
                                    <a class="skill-link" href="#">
                                        <img class="skill-img"
                                            src="{{ skill.image.url }}"
                                            alt="{{ skill.name }}">
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <p class="card-description">
                            {{ card.description }}
                        </p>
                    </div>
                    <img class="card-image"
                        src="{{ card.image.url }}"
                        alt="card-image">
                </div>
                {% endfor %}
            </div>
            {% if is_paginated %}
            <nav class="pagination">
                <div class="pagination-content">
                    <a href="{% if page_obj.has_previous %} {% url 'projects:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}">&laquo;</a>
                    {% for page in page_obj.paginator.page_range %}
                        {% if page == page_obj.number %}
                            <a href="{% url 'projects:paginator' page %}" class="active">{{ page }}</a>
                        {% else %}
                            <a href="{% url 'projects:paginator' page %}">{{ page }}</a>
                        {% endif %}
                    {% endfor %}
                    <a href="{% if page_obj.has_next %} {% url 'projects:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">&raquo;</a>
                </div>
            </nav>
            {% endif %}

  {% endblock %}